qq_bot:
  cqhttp_url: http://127.0.0.1:8600
  bot_uid: '1877200940'
  admin_qq: '1181806270'
  host: 127.0.0.1
  port: 5555
  max_length: 4500
  auto_confirm: false
  bot_name: yumi二号机
openai:
  endpoints:
    - api_key: '1'
      priority: 1
      url: https://free.oneai.buzz/v1
    - api_key: '1'
      priority: 2
      url: https://free.zeroai.chat/v1
    - api_key: sk-LI5WPEH3R6cZZGEz00E504C747D34a408574E5B3F87fBf03
      priority: 3
      url: https://ai.zeroai.one/v1
  img_size: 1024x1024
chatgpt:
  model: gpt-4o
  max_tokens: 4000
  preset: 你是一个智能助手...
  functions_enabled: true
baidu:
  appid: 你的百度翻译APPID
  secret_key: 你的百度翻译密钥
replicate:
  api_token: 你的Replicate API Token
electricity:
  api_url: 电费查询API地址
  api_key: 电费查询API密钥
news:
  gid:
    cs2: CS2新闻推送群号,多个群用逗号分隔
    gpt: GPT新闻推送群号,多个群用逗号分隔
database:
  path: data/bot.db
google:
  api_key: 你的Google API密钥
  cx_id: 你的自定义搜索引擎ID
  serper_api_key: 你的Serper API密钥
