qq_bot:
  cqhttp_url: "http://127.0.0.1:8600" # cqhttp地址
  bot_uid: "你的机器人QQ号" # 机器人QQ号
  admin_qq: "管理员QQ号" # 管理员QQ号
  host: "127.0.0.1" # 服务器地址
  port: 5555 # 服务器端口
  max_length: 4500 # 消息最大长度
  auto_confirm: false # 是否自动确认好友请求
  bot_name: "yumi" # 机器人昵称


openai:
  api_key: 
    - "你的OpenAI API Key" # OpenAI API Key
  base_urls:
    - url: "https://api.openai.com/v1"  # 官方API
      priority: 1
    - url: "https://your-proxy1.com/v1"  # 代理1
      priority: 2
    - url: "https://your-proxy2.com/v1"  # 代理2
      priority: 3
  img_size: "1024x1024" # 图片尺寸

chatgpt:
  model: "gpt-3.5-turbo-0613" # 模型
  max_tokens: 4000
  preset: "你是一个智能助手..." # 预设
  functions_enabled: true # 是否启用函数

baidu:
  appid: "你的百度翻译APPID" # 百度翻译APPID
  secret_key: "你的百度翻译密钥" # 百度翻译密钥

replicate:
  api_token: "你的Replicate API Token" # Replicate API Token

electricity:
  api_url: "电费查询API地址" # 电费查询API地址
  api_key: "电费查询API密钥" # 电费查询API密钥

news:
  gid:
    cs2: "CS2新闻推送群号,多个群用逗号分隔" # CS2新闻推送群号,多个群用逗号分隔
    gpt: "GPT新闻推送群号,多个群用逗号分隔" # GPT新闻推送群号,多个群用逗号分隔

database:
  path: "data/bot.db" # 数据库路径

google:
  api_key: "你的Google API密钥" # Google API密钥
  cx_id: "你的自定义搜索引擎ID" # 自定义搜索引擎ID
  serper_api_key: "你的Serper API密钥" # Serper API密钥
